name: Unit Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: [main, dev]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          npm install 
          npm test
          
      - name: Lint
        run: npm run lint